### ISSUE TITLE
Splitting training, test and validation data

### ISSUE THREAD

**Issue by fabianjaeger1** [thorben-frank/mlff#3]
Hey,

I was wondering if there is a possibility to include (or if there are any plans) to allow for the the option of loading separate training, test and validation sets instead of a single large input file?

Cheers,
Fabian

**Comment by thorben-frank** [comment]
Hi Fabian,

currently there is no straight forward way of doing this using the command line tool. Is my assumption correct that you are running training via the `train_so3krates` command?

Best,
~ Thorben

**Comment by fabianjaeger1** [comment]
Hey Thorben,

Thanks for reaching out. 

I was initially trying to run with the CLI tool but then tried circumventing the random split through the python code example you provided in the repo (train_so3krates.py) by essentially just using the index split and feeding the correct ids for each set into that method (see section marked below with "Main Changes to the original Code") but then I get the error message listed below the code snippet. But I am sure i'm overlooking something crucial. 

Thanks for your help!

Best
Fabian 

```
import numpy as np
import jax
import jax.numpy as jnp
import os
import wandb
import ase.units as si
from pathlib import Path
from mlff.data import AseDataLoader

from mlff.io.io import create_directory, bundle_dicts, save_dict
from mlff.training import Coach, Optimizer, get_loss_fn, create_train_state
from mlff.data import DataTuple, DataSet

from mlff.nn.stacknet import get_obs_and_force_fn, get_observable_fn, get_energy_force_stress_fn
from mlff.nn import So3krates

import mlff.properties.property_names as pn
from mlff.properties import md17_property_keys


save_path = 'ckpt_dir'
data_parent_path = "../data/1000000000"
data_path = "{}/data_combined.xyz".format(data_parent_path)
data_path = Path(data_path).absolute().resolve().as_posix()

ckpt_dir = os.path.join(save_path, 'module')
ckpt_dir = create_directory(ckpt_dir, exists_ok=False)

prop_keys = md17_property_keys

r_cut = 5

inputs = [pn.atomic_type, pn.atomic_position, pn.idx_i, pn.idx_j, pn.node_mask]
target_quantities = [pn.energy, pn.force, pn.stress]

# Currently not implemented
mic = False

if mic:
    inputs += [pn.unit_cell]
    inputs += [pn.cell_offset]


data_loader = AseDataLoader(data_path, load_stress=True)
data = data_loader.load_all()

data_set = DataSet(data=data, prop_keys=prop_keys)


########################
# Main Changes to the original Code

idx_train = list(range(230185))
idx_val = list(range(2308185,242997, 1))
idx_test = list(range(242997,255835, 1))

data_set.index_split(data_idx_train = idx_train, data_idx_valid = idx_val, data_idx_test = idx_test, training=True, r_cut =r_cut, mic=mic)

# returns the split datasets
d = data_set.get_data_split()

########################

net = So3krates(F=32,
                n_layer=2,
                prop_keys=prop_keys,
                geometry_embed_kwargs={'degrees': [1, 2],
                                       'r_cut': r_cut
                                       },
                so3krates_layer_kwargs={'n_heads': 2,
                                        'degrees': [1, 2]})

obs_fn = get_obs_and_force_fn(net)
obs_fn = jax.vmap(obs_fn, in_axes=(None, 0))

opt = Optimizer()

tx = opt.get(learning_rate=1e-3)

coach = Coach(inputs=input_quantities,
              targets=target_quantities,
              epochs=1000,
              training_batch_size=5,
              validation_batch_size=5,
              loss_weights={pn.energy: .01, pn.force: 0.99},
              ckpt_dir=ckpt_dir,
              data_path=train_path,
              net_seed=0,
              training_seed=0)

loss_fn = get_loss_fn(obs_fn=obs_fn,
                      weights=coach.loss_weights,
                      prop_keys=prop_keys)

data_tuple = DataTuple(inputs=coach.inputs,
                       targets=coach.targets,
                       prop_keys=prop_keys)

train_ds = data_tuple(d['train'])
valid_ds = data_tuple(d['valid'])

inputs = jax.tree_map(lambda x: jnp.array(x[0, ...]), train_ds[0])
params = net.init(jax.random.PRNGKey(coach.net_seed), inputs)
train_state, h_train_state = create_train_state(net,
                                                params,
                                                tx,
                                                polyak_step_size=None,
                                                plateau_lr_decay={'patience': 50,
                                                                  'decay_factor': 1.
                                                                  },
                                                scheduled_lr_decay={'exponential': {'transition_steps': 10_000,
                                                                                    'decay_factor': 0.9}
                                                                    }
                                                )

h_net = net.__dict_repr__()
h_opt = opt.__dict_repr__()
h_coach = coach.__dict_repr__()
h_dataset = data_set.__dict_repr__()
h = bundle_dicts([h_net, h_opt, h_coach, h_dataset, h_train_state])
save_dict(path=ckpt_dir, filename='hyperparameters.json', data=h, exists_ok=True)

wandb.init(config=h)
coach.run(train_state=train_state,
          train_ds=train_ds,
          valid_ds=valid_ds,
          loss_fn=loss_fn,
          ckpt_overwrite=True,
          log_every_t=1,
          restart_by_nan=True,
          use_wandb=True)
```

```
data_set.index_split(data_idx_train = idx_train, data_idx_valid = idx_val, data_idx_test = idx_test, training=True, r_cut =r_cut, mic=mic)
  File "/cluster/home/jaegerf/mlff/mlff/data/dataset.py", line 183, in index_split
    neigh_idxs = get_indices(R_dat, z_dat, r_cut=r_cut)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/jaegerf/mlff/mlff/indexing/indices.py", line 69, in get_indices
    idxs = list(map(get_idx, tqdm(range(n_data))))  # [(2,*), ..., (2,*)]  * is number of pairs per point
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/jaegerf/mlff/mlff/indexing/indices.py", line 63, in get_idx
    idx_ = idx[:, neigh_filter(z[i], R[i], cell[i])]  # shape: (2,n_pairs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/jaegerf/miniconda3/envs/ml_env/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/jaegerf/miniconda3/envs/ml_env/lib/python3.11/site-packages/jax/_src/pjit.py", line 208, in cache_miss
    outs, out_flat, out_tree, args_flat = _python_pjit_helper(
                                          ^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/jaegerf/miniconda3/envs/ml_env/lib/python3.11/site-packages/jax/_src/pjit.py", line 155, in _python_pjit_helper
    out_flat = pjit_p.bind(*args_flat, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/jaegerf/miniconda3/envs/ml_env/lib/python3.11/site-packages/jax/_src/core.py", line 2633, in bind
    return self.bind_with_trace(top_trace, args, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/jaegerf/miniconda3/envs/ml_env/lib/python3.11/site-packages/jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/jaegerf/miniconda3/envs/ml_env/lib/python3.11/site-packages/jax/_src/core.py", line 790, in process_primitive
    return primitive.impl(*tracers, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/jaegerf/miniconda3/envs/ml_env/lib/python3.11/site-packages/jax/_src/pjit.py", line 1088, in _pjit_call_impl
    always_lower=False, lowering_platform=None).compile()
                                                ^^^^^^^^^
  File "/cluster/home/jaegerf/miniconda3/envs/ml_env/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 2313, in compile
    executable = UnloadedMeshExecutable.from_hlo(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/jaegerf/miniconda3/envs/ml_env/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 2633, in from_hlo
    xla_executable, compile_options = _cached_compilation(
                                      ^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/jaegerf/miniconda3/envs/ml_env/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 2551, in _cached_compilation
    xla_executable = dispatch.compile_or_get_cached(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/jaegerf/miniconda3/envs/ml_env/lib/python3.11/site-packages/jax/_src/dispatch.py", line 495, in compile_or_get_cached
    return backend_compile(backend, computation, compile_options,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/jaegerf/miniconda3/envs/ml_env/lib/python3.11/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/jaegerf/miniconda3/envs/ml_env/lib/python3.11/site-packages/jax/_src/dispatch.py", line 463, in backend_compile
    return backend.compile(built_c, compile_options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.
```

**Comment by thorben-frank** [comment]
Hi Fabian, 

I tried to reproduce the error on my local machine (with a different and probably smaller`.xyz` file) and for me your code is running fine. 

I noticed that your training file seems to be rather big so there might be some memory issues which potentially can cause such cryptic stack trace. Could you try to use e.g. 
```python
idx_train = list(range(1000))
idx_val = list(range(1000,2000 1))
idx_test = list(range(2000,3000 1))
```
just to exclude this possibility. Are you running on CPU or GPU? And what is the largest, smallest structure in your data set?

~ Thorben

**Comment by fabianjaeger1** [comment]
I tried running it with the idx above but still run into the same issue. Below you can find the error message.

I am technically running the code on a V100 right now but there seems to be a cudnn error below, so maybe that is the cause?

And the structures are ranging from 2 to max 20 sites.

```
INFO:root:Generate neighborhood lists for 2000 geometries:
^M  0%|          | 0/2000 [00:00<?, ?it/s]INFO:jax._src.xla_bridge:Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: CUDA Interpreter Host
INFO:jax._src.xla_bridge:Unable to initialize backend 'tpu': module 'jaxlib.xla_extension' has no attribute 'get_tpu_client'
2023-06-02 12:22:06.614463: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:407] There was an error before creating cudnn handle (302): cudaGetErrorName symbol not found. : cudaGetErrorString symbol not found.
^M  0%|          | 0/2000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/cluster/scratch/jaegerf/ML/so3krates/train_so3krates_mod.py", line 63, in <module>
    data_set.index_split(data_idx_train = idx_train, data_idx_valid = idx_val, data_idx_test = idx_test, training=True, r_cut =r_cut, mic=mic)
  File "/cluster/home/jaegerf/mlff/mlff/data/dataset.py", line 183, in index_split
    neigh_idxs = get_indices(R_dat, z_dat, r_cut=r_cut)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/jaegerf/mlff/mlff/indexing/indices.py", line 69, in get_indices
    idxs = list(map(get_idx, tqdm(range(n_data))))  # [(2,*), ..., (2,*)]  * is number of pairs per point
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/jaegerf/mlff/mlff/indexing/indices.py", line 63, in get_idx
    idx_ = idx[:, neigh_filter(z[i], R[i], cell[i])]  # shape: (2,n_pairs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/jaegerf/miniconda3/envs/ml_env/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/jaegerf/miniconda3/envs/ml_env/lib/python3.11/site-packages/jax/_src/pjit.py", line 208, in cache_miss
    outs, out_flat, out_tree, args_flat = _python_pjit_helper(
                                          ^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/jaegerf/miniconda3/envs/ml_env/lib/python3.11/site-packages/jax/_src/pjit.py", line 155, in _python_pjit_helper
    out_flat = pjit_p.bind(*args_flat, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/jaegerf/miniconda3/envs/ml_env/lib/python3.11/site-packages/jax/_src/core.py", line 2633, in bind
    return self.bind_with_trace(top_trace, args, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/jaegerf/miniconda3/envs/ml_env/lib/python3.11/site-packages/jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/jaegerf/miniconda3/envs/ml_env/lib/python3.11/site-packages/jax/_src/core.py", line 790, in process_primitive
    return primitive.impl(*tracers, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/jaegerf/miniconda3/envs/ml_env/lib/python3.11/site-packages/jax/_src/pjit.py", line 1088, in _pjit_call_impl
    always_lower=False, lowering_platform=None).compile()
                                                ^^^^^^^^^
  File "/cluster/home/jaegerf/miniconda3/envs/ml_env/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 2313, in compile
    executable = UnloadedMeshExecutable.from_hlo(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/jaegerf/miniconda3/envs/ml_env/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 2633, in from_hlo
    xla_executable, compile_options = _cached_compilation(
                                      ^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/jaegerf/miniconda3/envs/ml_env/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 2551, in _cached_compilation
    xla_executable = dispatch.compile_or_get_cached(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/jaegerf/miniconda3/envs/ml_env/lib/python3.11/site-packages/jax/_src/dispatch.py", line 495, in compile_or_get_cached
    return backend_compile(backend, computation, compile_options,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/jaegerf/miniconda3/envs/ml_env/lib/python3.11/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/jaegerf/miniconda3/envs/ml_env/lib/python3.11/site-packages/jax/_src/dispatch.py", line 463, in backend_compile
    return backend.compile(built_c, compile_options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/cluster/scratch/jaegerf/ML/so3krates/train_so3krates_mod.py", line 63, in <module>
    data_set.index_split(data_idx_train = idx_train, data_idx_valid = idx_val, data_idx_test = idx_test, training=True, r_cut =r_cut, mic=mic)
  File "/cluster/home/jaegerf/mlff/mlff/data/dataset.py", line 183, in index_split
    neigh_idxs = get_indices(R_dat, z_dat, r_cut=r_cut)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/jaegerf/mlff/mlff/indexing/indices.py", line 69, in get_indices
    idxs = list(map(get_idx, tqdm(range(n_data))))  # [(2,*), ..., (2,*)]  * is number of pairs per point
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/jaegerf/mlff/mlff/indexing/indices.py", line 63, in get_idx
    idx_ = idx[:, neigh_filter(z[i], R[i], cell[i])]  # shape: (2,n_pairs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.

```

**Comment by thorben-frank** [comment]
there might be an issue with the cuda installation .. did you install `jax` and `jaxlib` yourself or is it pre-installed on your cluster? Which CUDA version is installed?

Here (https://github.com/jkulhanek/tetra-nerf/issues/7), it seems that this error can appear when the CUDA version does not match with the installed JAX version ... 

I think you can check if it is a problem with you jax installation by running a simple script e.g.

```python
import jax.numpy as jnp
from jax import jit

def slow_f(x):
  return x * x + x * 2.0

x = jnp.ones((5000, 5000))
fast_f = jit(slow_f)
fast_f(x)
slow_f(x)
```

**Comment by thorben-frank** [comment]
Assuming the installed JAX with the command given in the `mlff` readme [here](https://github.com/thorben-frank/mlff#installation):
 
I checked the JAX docs [here](https://github.com/google/jax#pip-installation-gpu-cuda-installed-via-pip-easier) and it seems that the command which is given in the `mlff` readme to install JAX is outdated. The new commands are, depending on your cuda version
```
pip install --upgrade pip

# CUDA 12 installation
# Note: wheels only available on linux.
pip install --upgrade "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

# CUDA 11 installation
# Note: wheels only available on linux.
pip install --upgrade "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```

I think its worth checking if re-installing JAX with the new commands might solve the problem.

**Comment by fabianjaeger1** [comment]
Hey Thorben,

Thanks for the info. You were right, it seemed to be some cuda error. I reinstalled jax and jaxlib again and it seems to work now.

Thanks for the help!

Cheers, 
Fabian
